dukapoint/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from dukapoint import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name='home'),
    path('suppliers/', include('suppliers.urls', namespace='suppliers')),
    path('sales/', include('sales.urls', namespace='sales')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('products/', include('products.urls', namespace='products')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('branches/', include('branches.urls', namespace='branches')),
    path('deliveries/', include('deliveries.urls', namespace='deliveries')),
    path('returns/', include('returns.urls', namespace='returns')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from sales import views

app_name = 'sales'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('search-products', views.SearchProducts.as_view(), name='search-products'),
    path('add-to-cart', views.AddToCart.as_view(), name='add-to-cart'),
    path('clear-cart', views.ClearCart.as_view(), name='clear-cart'),
    path('delete-from-cart/<int:product_id>/', views.DeleteCartProduct.as_view(), name='delete-from-cart'),
    path('check-out/', views.CheckOut.as_view(), name='check-out'),
    path('reports-home/', views.ReportsHome.as_view(), name='reports-home'),
]

sales/models.py
from django.db import models
from products.models import Product
from customers.models import Customer
from staff.models import Staff
from branches.models import Branch


class Sale(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    datetime = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.PROTECT)
    unit_price = models.FloatField(default=0.0)
    quantity = models.IntegerField(default=1)
    total = models.FloatField(default=0.0)
    staff = models.ForeignKey(Staff, on_delete=models.PROTECT, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.PROTECT, null=True)

    def __str__(self):

        return self.product.name

sales/forms.py
from django import forms
from branches.models import Branch


class SalesFiltersForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['date_from'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_from'].widget.attrs.update({'placeholder': 'Date from'})
        self.fields['date_to'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_to'].widget.attrs.update({'placeholder': 'Date to'})
        self.fields['branch'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_from'].widget.attrs.update({'id': 'date_from'})
        self.fields['date_to'].widget.attrs.update({'id': 'date_to'})

    date_from = forms.DateField()
    date_to = forms.DateField()
    branch = forms.ModelChoiceField(
        queryset=Branch.objects.all(),
        # required=False
    )


class SaleForm(forms.Form):

    confirm_sale = forms.CharField(max_length=150)


class AddToCartForm(forms.Form):

    product_name = forms.CharField(max_length=150)
    unit_price = forms.FloatField(initial=0.0)
    quantity = forms.IntegerField(initial=1)
    total = forms.FloatField(initial=1.0)
    product_id = forms.IntegerField()

sales/views.py
from django.views.generic import TemplateView, FormView, ListView
from django.contrib.auth.mixins import PermissionRequiredMixin
import json
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from products.models import Product, BranchProduct
from sales.forms import AddToCartForm, SaleForm, SalesFiltersForm
from django.shortcuts import redirect, render
from django.contrib import messages
from sales.models import Sale
from deliveries.models import Stock
from django.db.models import Sum
from django.conf import settings


class ReportsHome(PermissionRequiredMixin, FormView):
    permission_required = ["sales.view_sale"]
    raise_exception = True
    permission_denied_message = "You dont have permission to view sales"
    template_name = 'sales/reports_home.html'
    form_class = SalesFiltersForm

    def post(self, request, *args, **kwargs):

        context = super().get_context_data(**kwargs)

        form = self.form_class(data=request.POST)

        if form.is_valid():

            context['sale_list'] = Sale.objects.filter(
                datetime__gte=str(form.cleaned_data['date_from']) + " 00:00:00",
                datetime__lte=str(form.cleaned_data['date_to']) + " 23:59:59",
                branch_id=form.cleaned_data['branch']
            )

            context['sum'] = context['sale_list'].aggregate(Sum('total'))

        return render(request, self.template_name, context=context)

    def get(self, request, *args, **kwargs):

        context = super().get_context_data(**kwargs)

        if request.GET.get("date_from"):

            context['sale_list'] = Sale.objects.filter(
                datetime__gte=request.GET.get("date_from"),
                datetime__lte=request.GET.get("date_to"),
                branch_id=request.GET.get("branch")
            )
        else:
            context['sale_list'] = Sale.objects.all()

        context['sum'] = context['sale_list'].aggregate(Sum('total'))

        return render(request, self.template_name, context=context)


class CheckOut(PermissionRequiredMixin, FormView):
    permission_required = ["sales.add_sale"]
    raise_exception = True
    permission_denied_message = "You dont have permission to add sales"
    form_class = SaleForm
    template_name = 'sales/check_out.html'

    def post(self, request, *args, **kwargs):

        products_list = []

        for product in request.session['cart_products']:

            product_obj = Product.objects.get(pk=product['product_id'])

            sale = Sale(
                product_id=product['product_id'],
                quantity=product['quantity'],
                unit_price=product['unit_price'],
                total=product['unit_price']*product['quantity'],
                staff_id=self.request.user.pk,
                branch_id=self.request.user.branch.pk,
            )

            sale.save()

            # Update product_stock
            product_obj.quantity = product_obj.quantity - product['quantity']
            product_obj.save()

            # Update branch_stock tbl

            branch_stock, created = BranchProduct.objects.get_or_create(
                product_id=product_obj.pk,
                branch_id=request.user.branch.pk
            )

            branch_stock.quantity = branch_stock.quantity - product['quantity']

            branch_stock.save()

        #     Build list dictionary for printing
            if settings.PRINT_RECEIPTS:
                products_list.append({
                    'product_id': product_obj.pk,
                    'product_name': product_obj.name,
                    'quantity': product['quantity'],
                    'unit_price': product['unit_price'],
                    'total': product['unit_price']*product['quantity'],
                    'sale_total': sale.total,
                })

        del request.session['cart_products']
        messages.success(request, 'Sale completed successfully', extra_tags='alert alert-success')

        return redirect(to='/sales/')

    def get(self, request, *args, **kwargs):

        if 'cart_products' in request.session.keys():
            data = request.session['cart_products']
        else:
            data = None

        return render(request, self.template_name, {'cart_products': data})


class DeleteCartProduct(PermissionRequiredMixin, TemplateView):
    permission_required = ["sales.add_sale"]
    permission_denied_message = "You dont have permission to make sales"
    raise_exception = True

    def get(self, request, *args, **kwargs):

        if 'cart_products' in request.session.keys():

            if self.kwargs['product_id'] in [p['product_id'] for p in request.session['cart_products']]:

                cart_products = request.session['cart_products']

                for product in cart_products:

                    if product['product_id'] == self.kwargs['product_id']:

                        cart_products.remove(product)

                        request.session['cart_products'] = cart_products

                        messages.success(request, 'Success, product has been removed', extra_tags='alert alert-info')

            else:

                messages.error(request, 'Product not in cart', extra_tags='alert alert-danger')
        else:
            messages.info(request, 'Alert!, shopping cart is empty', extra_tags='alert alert-info')

        return redirect(to='/sales/')


class AddToCart(PermissionRequiredMixin, FormView):
    """Adds items to session"""
    permission_required = ["sales.add_sale"]
    raise_exception = True
    permission_denied_message = "You dont have permission to make sales"
    form_class = AddToCartForm

    def post(self, request, *args, **kwargs):

        form = self.form_class(data=request.POST)

        if form.is_valid():

            product_name = form.cleaned_data['product_name']
            quantity = form.cleaned_data['quantity']
            unit_price = form.cleaned_data['unit_price']
            product_id = form.cleaned_data['product_id']

            new_product = {
                'product_name': product_name,
                'product_id': product_id,
                'unit_price': unit_price,
                'total': quantity * unit_price,
                'quantity': quantity,
            }

            if 'cart_products' not in request.session.keys():  # add first product to cart_products list

                cart_products = list()

                cart_products.append(new_product)

                request.session['cart_products'] = cart_products

            else:

                cart_products = request.session['cart_products']
                product_ids = [pk['product_id'] for pk in cart_products]

                if new_product['product_id'] not in product_ids:

                    cart_products.append(new_product)
                else:

                    for product in cart_products:

                        quantity = product['quantity'] + new_product['quantity']
                        total = quantity * new_product['unit_price']

                        if product['product_id'] == new_product['product_id']:
                            product['quantity'] = quantity
                            product['unit_price'] = new_product['unit_price']
                            product['total'] = total

                request.session['cart_products'] = cart_products

        else:
            cart_products = {"error": form.errors}

        return HttpResponse(
            json.dumps(cart_products),
            content_type="text/json"
        )


class Home(PermissionRequiredMixin, TemplateView):
    permission_required = ['sales.add_sale']
    template_name = 'sales/pos.html'
    raise_exception = True
    permission_denied_message = "You dont have permission to make sales"

    def get(self, request, *args, **kwargs):

        if 'cart_products' in request.session.keys():
            data = request.session['cart_products']
        else:
            data = None

        return render(request, self.template_name, {'cart_products': data})


class ClearCart(PermissionRequiredMixin, TemplateView):
    permission_required = ['sales.add_sale']
    raise_exception = True
    permission_denied_message = "You dont have permission to make sales"

    def get(self, request, *args, **kwargs):

        if 'cart_products' in request.session.keys():

            del request.session['cart_products']
        else:
            pass

        return redirect(to='/sales/')


class SearchProducts(PermissionRequiredMixin, FormView):
    permission_required = ['sales.add_sale']
    permission_denied_message = "You dont have permission to make sales"
    raise_exception = True

    def get(self, request, *args, **kwargs):

        try:
            products = Stock.objects.filter(
                product__name__contains=request.GET.get('product'),
                current_branch_id=request.user.branch_id
            ).reverse()

            product_list = []
            product_names = []

            for item in products:

                if item.product.name not in product_names:

                    product_list.append({
                        'name': item.product.name,
                        'id': item.product.pk,
                        'quantity': item.quantity,
                        'retail_price': item.retail_price,
                        'wholesale_price': item.wholesale_price,
                        'buying_price': item.buying_price,
                    })

                    product_names.append(item.product.name)

            response = json.dumps(product_list)

        except ObjectDoesNotExist as exp:

            err_str = str(exp) + str(" or not active")

            response = json.dumps({'err': err_str})

        return HttpResponse(response, content_type="text/json")

templates/sales/check_out.html
{% extends 'base.html' %}
        {% load static %}
{% block page_style %}
        <style>
            th{background-color: rgb(233, 236, 239);}
            .fa-trash-alt, .fa-trash{color: red;}
        </style>
{% endblock page_style %}
{% block page_js %}{% endblock page_js %}

{% block page_content %}
    {% include 'messages.html' %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body text-center">
                    {% if cart_products|length > 0 %}
                        <form method="post" action="{% url 'sales:check-out' %}" id="checkout-form">{% csrf_token %}
                            <input name="confirm_sale" type="hidden" />
                            <p>Proceed to check-out ?</p>
                            <button type="submit" class="btn btn-info btn-block btn-lg">
                                <i class="fa fa-check-circle"> </i> Check-out
                            </button>
                        </form>
                    {% else %}
                        <div class="alert alert-info">
                            Nothing to checkout, <a href="{% url 'sales:home' %}"> go to POS.</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-8">
                            <h4 class="card-title mb-0"><i class="fa fa-shopping-cart"></i> Shopping Cart</h4>
                        </div>
                        <div class="col-4" id="cart-total">
                            <h4 class="card-title mb-0">KES : 0.0</h4>
                        </div>
                    </div>

                </div>
                <div class="card-body">
                    <div id="cart-contents">
                        {% if cart_products|length > 0 %}
                            <table class='table table-bordered' id='cart-table'>
                                <thead><th></th><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></thead>
                                <tbody>
                                    {% for product in cart_products %}
                                        <tr id='{{ product.product_id }}'>
                                            <td>
                                                <a href="{% url 'sales:delete-from-cart' product_id=product.product_id %}">
                                                    <i class="fa fa-trash-alt"></i>
                                                </a>
                                            </td>
                                            <td>{{ product.product_name }}</td>
                                            <td>{{ product.quantity }}</td>
                                            <td>{{ product.unit_price }}</td>
                                            <td class="product_total">{{ product.total }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                        {% else %}
                            <div class="alert alert-info" id="cart-alert">No items, shopping cart is empty</div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {

        let cart_total = 0.0;
        let product_totals = document.getElementsByClassName('product_total');

        let i;
        for (i = 0; i < product_totals.length; i++) {
            cart_total += parseFloat(product_totals[i].textContent);
        }

        $('#cart-total').html("<h4 class='card-title mb-0'>KES : "+cart_total+"</h4>");

    });
    </script>

{% endblock page_content %}

templates/sales/pos.html
{% extends 'base.html' %}

{% load static %}
{% block page_style %}
		<link href="{% static 'autocomplete/easy-autocomplete.min.css' %}" rel="stylesheet" type="text/css">
        <style>
            th{background-color: rgb(233, 236, 239);}
            .fa-trash-alt, .fa-trash{color: red;}
        </style>
{% endblock page_style %}
{% block page_js %}
		<script src="{% static 'autocomplete/jquery-1.11.2.min.js' %}"></script>
		<script src="{% static 'autocomplete/jquery.easy-autocomplete.min.js' %}" type="text/javascript" ></script>
{% endblock page_js %}

{% block page_content %}
    {% include 'messages.html' %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <input id="product-search" class="form-control" />
                </div>
            </div>
            <div class="card mt-3">
                <div class="card-body text-center">
                    <div id="product-details">
                        <form style="display: none;" id="sales_form" >{% csrf_token %}
                            <h4 id="product_name" class="bg-dark text-white pt-2 pb-2 mb-0"></h4>
                            <table class="table table-bordered">
                                <thead class="bg-light">
                                    <th>Price</th><th>Qty</th><th>Total</th>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><input class="form-control" name="unit_price" id="unit_price"></td>
                                        <td><input type="number" min="1" class="form-control" name="quantity" id="quantity"></td>
                                        <td><input class="form-control" name="total" id="total"></td>
                                    </tr>
                                </tbody>
                            </table>
                            <input type="hidden" name="product_name" id="product">
                            <input type="hidden" name="product_id" id="product_pk">
                            <button class="btn btn-info justify-content-end" type="submit">
                                Add to Cart <i class="fa fa-cart-plus"></i>
                            </button>
                        </form>
                    </div>
                    <p class="small" id="search-instructions">Search products to start selling</p>
                </div>
            </div>

        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-8">
                            <h4 class="card-title mb-0"><i class="fa fa-shopping-cart"></i> Shopping Cart</h4>
                        </div>
                        <div class="col-4" id="cart-total">
                            <h4 class="card-title mb-0">KES : 0.0</h4>
                        </div>
                    </div>

                </div>
                <div class="card-body" id="product-details">
                    <div id="cart-contents">
                        {% if cart_products|length > 0 %}
                            <table class='table table-bordered' id='cart-table'>
                                <thead><th></th><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></thead>
                                <tbody>
                                    {% for product in cart_products %}
                                        <tr id='{{ product.product_id }}'>
                                            <td>
                                                <a href="{% url 'sales:delete-from-cart' product_id=product.product_id %}">
                                                    <i class="fa fa-trash-alt"></i>
                                                </a>
                                            </td>
                                            <td>{{ product.product_name }}</td>
                                            <td>{{ product.quantity }}</td>
                                            <td>{{ product.unit_price }}</td>
                                            <td class="product_total">{{ product.total }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                        {% else %}
                            <div class="alert alert-info" id="cart-alert">No items, shopping cart is empty</div>
                        {% endif %}
                    </div>
                    <div class="row">
                            <div class="col-6 text-center" id="cart-btns">
                                <a href="{% url 'sales:check-out' %}" class="btn btn-info">
                                    Check-out <i class="fa fa-flag-checkered"></i>
                                </a>
                            </div>
                            <div class="col-6 text-center">
                                <a href="{% url 'sales:clear-cart' %}" class="btn btn-outline-danger">Empty Cart
                                    <i class="fa fa-flag-checkered"></i>
                                </a>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>

    <script>

    $("#sales_form").submit(function () {

       let formData = $("#sales_form").serialize();

       $("input#product-search").val('');

       $.ajax({
           url: "{% url 'sales:add-to-cart' %}",
           data: formData,
           method: 'POST',
           success: function(reply){

               if(reply.error) {
                   $('#cart-contents').html(reply.error);
               }else {

                   $('#cart-contents').html('');

                   $('#cart-contents').append("<table class='table table-bordered' id='cart-table'></table>");

                   $('#cart-table').append("<th></th><th>Item</th><th>Qty</th><th>Price</th><th>Total</th>");

                   let cart_total = 0;

                   reply.forEach(function (item) {

                       cart_total = cart_total + parseInt(item.total);

                       $('#cart-table').append("<tr id='" + item.product_id + "'></tr>");
                       $("tr#" + item.product_id).append("<td><a href='/sales/delete-from-cart/"+item.product_id+"/'><i class='fa fa-trash'></i></a><td>" + item.product_name + "</td><td>" + item.quantity + "</td><td>" + item.unit_price + "</td><td>" + item.total + "</td>");

                       $('#cart-total').html("<h4 class='card-title mb-0'>KES : " + cart_total + "</h4>");
                   });
               }
           }
       });

       return false;
    });

    let options = {

        url: "{% url 'sales:search-products' %}?product=" + $("#product-search").val(),

        getValue: "name",

        template: {
            type: "description",
            fields: {
                description: "name"
            }
        },

        list: {
            match: {
                enabled: true,
            },
            onChooseEvent: function() {
                $("input#quantity").val(1);

                $("#search-instructions").hide(1000);
                $("#sales_form").show();

                let name = $("#product-search").getSelectedItemData().name;
                let quantity = $("#product-search").getSelectedItemData().quantity;
                let product_id = $("#product-search").getSelectedItemData().id;

                let retail_price = $("#product-search").getSelectedItemData().retail_price;
                let buying_price = $("#product-search").getSelectedItemData().buying_price;

                $("#product_name").html(name);

                $("input#quantity").attr("value", 1); //default qty is 1
                $("input#quantity").attr("max", parseInt(quantity)); //limit selling more than what is in store (works client-side only)

                $("input#unit_price").attr("value", retail_price); //default unit retail_price
                $("input#unit_price").attr("min", buying_price); //prevent selling item below buying price
                $("input#total").attr("value", retail_price); //default qty x price
                $("input#product_pk").attr("value", product_id);
                $("input#product").attr("value", name);

            }
        },

        theme: "plate-dark"
    };

    $("#product-search").easyAutocomplete(options);

    $("input#quantity").change(function () { // update total price when qty changes

        let qty = $("input#quantity").val();
        let price = $("input#unit_price").val();

        let total = qty * price;

        $("input#total").attr("value", total); //default qty x price
    });

    $("input#unit_price").keyup(function () { // update total price when unit price changes

        let qty = $("input#quantity").val();
        let price = $("input#unit_price").val();

        let total = qty * price;

        $("input#total").attr("value", total); //default qty x price
    });

    $(document).ready(function () {

        let cart_total = 0.0;
        let product_totals = document.getElementsByClassName('product_total');

        let i;
        for (i = 0; i < product_totals.length; i++) {
            cart_total += parseFloat(product_totals[i].textContent);
        }

        $('#cart-total').html("<h4 class='card-title mb-0'>KES : "+cart_total+"</h4>");

    });


    </script>
{% endblock page_content %}

templates/sales/reports_home.html
{% extends 'base.html' %}
        {% load static %}
{% block page_style %}
        <style>
            th{background-color: rgb(233, 236, 239);}
        </style>
{% endblock page_style %}
{% block page_js %}
    <script>
    $(document).ready(function () {

        $('#date_from').datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd-mm-yy'
        });
        $('#date_to' ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'dd-mm-yy'
        });
    });

    </script>
{% endblock page_js %}

{% block page_content %}
    {% include 'messages.html' %}
    <div class="card mb-2">
        <div class="card-body bg-light">{{ form_data }}
            <div class="row">
                <div class="col-8">
                    <form class="" method="post" action="{% url 'sales:reports-home' %}" id="sales_filters_form">
                        {% csrf_token %}
                        <div class="row">

                            <div class="col">
                                <div>{{ form.date_from }}</div>
                                <div>{{ form.date_from.errors }}</div>
                            </div>
                            <div class="col">
                                <div>{{ form.date_to }}</div>
                                <div>{{ form.date_to.errors }}</div>
                            </div>
                            <div class="col">
                                <div>{{ form.branch }}</div>
                                <div>{{ form.date_branch.errors }}</div>
                            </div>
                            <div class="col">
                                <div><button class="btn btn-info" type="submit">Update</button></div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-4 text-right">
                    <h4>Total <span class="badge badge-pill badge-danger">{{ sum.total__sum }}</span></h4>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            {% if sale_list|length > 0 %}
                <table class="table table-striped table-hover" id="myTable">
                    <thead>
                        <th>Date</th><th>Branch</th><th>Product</th><th>Qty</th><th>Price</th><th>Total</th>
                    </thead>
                    <tbody>
                        {% for sale in sale_list %}
                            <tr>
                                <td>{{ sale.datetime }}</td>
                                <td>{{ sale.branch.name }}</td>
                                <td>{{ sale.product.name }}</td>
                                <td>{{ sale.quantity }}</td>
                                <td>{{ sale.unit_price }}</td>
                                <td>{{ sale.total }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div class="alert alert-info">No sales have been made yet</div>
            {% endif %}
        </div>
    </div>

{% endblock page_content %}