customers/urls.py
from django.urls import path
from customers import views

app_name = 'customers'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('add-new/', views.CreateCustomer.as_view(), name='create-customer'),
    path('update-customer/<int:pk>', views.UpdateCustomer.as_view(), name='update-customer'),
    path('delete-customer/<int:pk>', views.DeleteCustomer.as_view(), name='delete-customer'),
]

dukapoint/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from dukapoint import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name='home'),
    path('suppliers/', include('suppliers.urls', namespace='suppliers')),
    path('sales/', include('sales.urls', namespace='sales')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('products/', include('products.urls', namespace='products')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('branches/', include('branches.urls', namespace='branches')),
    path('deliveries/', include('deliveries.urls', namespace='deliveries')),
    path('returns/', include('returns.urls', namespace='returns')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('create-product/', views.CreateProduct.as_view(), name='create-product'),
    path('update-product/<int:pk>/', views.UpdateProduct.as_view(), name='update-product'),
    path('delete-product/<int:pk>/', views.DeleteProduct.as_view(), name='delete-product'),
    path('product-detail/<int:pk>', views.ProductDetail.as_view(), name='product-detail'),
    path('view-transfers/', views.ViewTransfers.as_view(), name='view-transfers'),
    path('transfer-products/', views.TransferProducts.as_view(), name='transfer-products'),
    path('view-transfer-products/<int:transfer_id>', views.ViewTransferProducts.as_view(), name='view-transfer-products'),
    path('add-product/', views.AddProduct.as_view(), name='add-product'),
    path('delete-cart-product/<int:product_id>/', views.DeleterCartProduct.as_view(), name='delete-cart-product'),
    path('clear-list/', views.ClearList.as_view(), name='clear-list'),
    path('set-transfer-to/', views.SetTransferTo.as_view(), name='set-transfer-to'),
    path('process-transfer/', views.ProcessTransfer.as_view(), name='process-transfer'),
    path('receive-transfer/<int:transfer_id>/', views.ReceiveTransfer.as_view(), name='receive-transfer'),

]

sales/urls.py
from django.urls import path
from sales import views

app_name = 'sales'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('search-products', views.SearchProducts.as_view(), name='search-products'),
    path('add-to-cart', views.AddToCart.as_view(), name='add-to-cart'),
    path('clear-cart', views.ClearCart.as_view(), name='clear-cart'),
    path('delete-from-cart/<int:product_id>/', views.DeleteCartProduct.as_view(), name='delete-from-cart'),
    path('check-out/', views.CheckOut.as_view(), name='check-out'),
    path('reports-home/', views.ReportsHome.as_view(), name='reports-home'),
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('create-staff/', views.CreateStaff.as_view(), name='create-staff'),
    path('update-staff/<int:pk>/', views.UpdateStaff.as_view(), name='update-staff'),
    path('change-branch/', views.ChangeBranch.as_view(), name='change-branch'),
    path('update-password/<int:pk>/', views.UpdatePassword.as_view(), name='update-password'),
    path('set-permissions/<int:pk>/', views.SetPermissions.as_view(), name='set-permissions'),
    path('delete-staff/<int:pk>/', views.DeleteStaff.as_view(), name='delete-staff'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

suppliers/urls.py
from django.urls import path
from suppliers import views

app_name = 'suppliers'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('add-new/', views.CreateSupplier.as_view(), name='create-supplier'),
    path('update-supplier/<int:pk>', views.UpdateSupplier.as_view(), name='update-supplier'),
    path('delete-supplier/<int:pk>', views.DeleteSupplier.as_view(), name='delete-supplier'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Base POS :: {% block title %} {% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" href="{% static 'jquery-ui-1.12/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-4/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables/datatables.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/media-queries.css' %}">

    <script src="{% static 'jquery-ui-1.12/external/jquery/jquery.js' %}"></script>
    <script src="{% static 'jquery-ui-1.12/jquery-ui.min.js' %}"></script>
    <script src="{% static 'bootstrap-4/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/script.js' %}"></script>

    <script defer src="{% static 'fontawesome-5/js/fontawesome-all.min.js' %}"></script>
    <script defer src="{% static 'fontawesome-5/js/fa-v4-shims.min.js' %}"></script>
    <script defer src="{% static 'datatables/datatables.min.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#myTable').DataTable( {
                dom: 'Bfrtip',
                "pageLength": 50,
                buttons: [
                    'copy', 'excel', {
                        extend: 'pdfHtml5',
                        customize: function ( doc ) {
                            doc.content.splice( 1, 0, {} );
                        }
                    }, 'print'
                ]
            } );

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });

            $('#id_old_password').attr('class', 'form-control');
            $('#id_new_password1').attr('class', 'form-control');
            $('#id_new_password2').attr('class', 'form-control');

        });
    </script>
{% block page_style %}{% endblock page_style %}
{% block page_js %}{% endblock page_js %}

</head>
<body>
    <div class="wrapper">
    <!-- Sidebar  -->
    {% include 'sidebar.html' %}
    <!-- Page Content  -->

    <div id="content" class="container-fluid">
        <!-- Load top nav here -->
        {% include 'top-navigation.html' %}
        <div class="content p-4">
            {% block page_content %}{% endblock page_content %}
        </div>

    </div>
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %} Home{% endblock title %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="{{ message.tags }} alert-dismissible" id="" role="alert" {% endif %}>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"> &times; </span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

templates/sidebar.html
<nav id="sidebar">
        <div class="sidebar-header">
            <h3>Base POS</h3>
            <strong>BS</strong>
        </div>

        <ul class="list-unstyled components">
            <li class="sidebar-li">
                <a href="{% url 'home' %}"><i class="fas fa-home"></i> Home</a>
            </li>
            <li class="sidebar-li">
                <a href="#salesSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-handshake"></i> Sales
                </a>
                <ul class="collapse list-unstyled" id="salesSubmenu">
                    <li>
                        <a href="{% url 'sales:home' %}">
                            <i class="fa fa-list"></i> POS
                        </a>
                    </li>
                    <li>
                         <a href="{% url 'sales:reports-home' %}">
                             <i class="fa fa-shopping-bag"></i> Reports</a>
                    </li>
                    <li>
                         <a href="{% url 'returns:home' %}">
                             <i class="fa fa-shopping-bag"></i> Returns</a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-li">
                <a href="#productsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-shopping-basket"></i> Products
                </a>
                <ul class="collapse list-unstyled" id="productsSubmenu">
                    <li>
                        <a href="{% url 'products:home' %}">
                            <i class="fa fa-list"></i> View</a>
                    </li>
                    <li>
                         <a href="{% url 'products:create-product' %}">
                             <i class="fa fa-shopping-bag"></i> Add New</a>
                    </li>
                    <li>
                         <a href="{% url 'deliveries:home' %}">
                             <i class="fa fa-shopping-basket"></i> Deliveries</a>
                    </li>
                    <li>
                         <a href="{% url 'products:view-transfers' %}">
                             <i class="fa fa-shopping-basket"></i> Transfers</a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-li">
                <a href="#customersSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-handshake"></i> Customers
                </a>
                <ul class="collapse list-unstyled" id="customersSubmenu">
                    <li>
                        <a href="{% url 'customers:home' %}">
                            <i class="fa fa-list"></i> View
                        </a>
                    </li>
                    <li>
                         <a href="{% url 'customers:create-customer' %}">
                             <i class="fa fa-shopping-bag"></i> Add New</a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-li">
                <a href="#suppliersSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-truck"></i> Suppliers
                </a>
                <ul class="collapse list-unstyled" id="suppliersSubmenu">
                    <li>
                        <a href="{% url 'suppliers:home' %}">
                            <i class="fa fa-list"></i> View</a>
                    </li>
                    <li>
                         <a href="{% url 'suppliers:create-supplier' %}">
                             <i class="fa fa-user-plus"></i> Add New
                         </a>
                    </li>
                </ul>
            </li>
            <li class="sidebar-li">
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-users"></i> Staff
                </a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="{% url 'staff:home' %}">
                            <i class="fa fa-list"></i> View</a>
                    </li>
                    <li>
                        <a href="{% url 'staff:create-staff' %}">
                            <i class="fa fa-user-plus"></i> Add New</a>
                    </li>
                </ul>
            </li>

            <li class="sidebar-li">
                <a href="#systemSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-cog"></i> System
                </a>
                <ul class="collapse list-unstyled" id="systemSubmenu">
                    <li>
                        <a href="{% url 'branches:home' %}">
                            <i class="fa fa-code-branch"></i> Branches</a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-cog"></i> Administration </a>
                    </li>
                </ul>
            </li>
        </ul>

    </nav>

templates/top-navigation.html
<nav class="navbar navbar-expand-lg" style="background: #17a2b4;">
    <button type="button" id="sidebarCollapse" class="btn btn-info btn-sm rounded">
        <i class="fa fa-bars navbar-toggler-icon"></i>
    </button>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'sales:home' %}">
                    POS <span class="text-white">
                    {% if request.user.branch %}
                        @{{ request.user.branch.name|truncatechars:10 }}
                    {% endif %}</span>
                </a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user" style="color:rd"></i> <strong>{{ request.user.last_name }}</strong>
                    </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url 'staff:update-staff' pk=request.user.pk %}">My Profile</a>
                          <a class="dropdown-item" href="{% url 'staff:change-branch' %}">Change branch</a>
                          <a class="dropdown-item" href="{% url 'staff:logout' %}">Logout</a>
                        </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'staff:login' %}">
                        <i class="fa fa-sign-in-alt"></i> Login
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>

</nav>